# Python Bootcamp Day 1:
## Introduction to Python and Jupyter

## Goals for the Lesson
Continuing directly from the last lesson,
- Code Basics
    - Data Types 
    - Functions
- Code Flow
    - Making Separate Python Files
    - Using Packages
    - Code Flow
    

## 1.5 Data Types in Python

So far, we have only worked with singular numerical data. Python can do a lot more than that. Before exploring non-numerical data, let's look at storing multiple pieces of numerical data at once in lists. These are basic forms of vectors and we'll come back to this idea later when we explore packages like NumPy, Pandas, and Xarray.

To start, creating a list is easy if you already know the entries you want to put in. Using the `[]` around the list of numbers and saving that into a variable does the trick.

<span style="color:blue">Task: Run the next cell</span>

In [1]:
my_list = [1,2,3]
print(my_list)

[1, 2, 3]


When using data that has multiple entries saved into one variable name like `my_list`, the syntax rule for accessing just one piece of that data is using the variable name followed by the **index** number of the entry you'd like in `[]` like this example: `variable[0]`.

Note: **Python starts index counting at 0**, so the first entry is at location 0 and the second entry is at location 1. This is not the same for all languages. Matlab is another popular programming language, and it starts at index 1.

<span style="color:blue">Task: Run the following blocks of code. </span>

In [2]:
print(my_list[0])

1


In [3]:
print(my_list[1])

2


In [4]:
print(my_list[2])

3


In [5]:
list_total = my_list[0] + my_list[1] + my_list[2]
print("The sum total of the list is ", list_total)

The sum total of the list is  6


There are a lot of data types in Python. We will give you a brief outline of a few other types besides numbers today, and we will help you by showing you how to see the type of a variable using the `type()` function. We'll cover functions in the next section. As we keep expanding your python knowledge you will find there are more than just these basic types of data in Python, and we will talk about those as they come up.

For more information on the basic types Python has to offer, there is a good intro [here](https://www.w3schools.com/python/python_datatypes.asp)

<span style="color:blue">Task: Run the following blocks and try making your own variables of each type.</span>

In [6]:
# String
a_string = "Hello world"
print("a_string has the value ", a_string)
print("a_string is of type ", type(a_string))

a_string has the value  Hello world
a_string is of type  <class 'str'>


In [ ]:
# Make your own string here:



In [7]:
# Integer
an_integer = 20
print("an_integer has the value ", an_integer)
print("an_integer is of type ", type(an_integer))

an_integer has the value  20
an_integer is of type  <class 'int'>


In [ ]:
# Make your own integer here:



In [8]:
# Floating Point Number (Decimal number)
a_float = 20.5
print("a_float has the value ", a_float)
print("a_float is of type ", type(a_float))

a_float has the value  20.5
a_float is of type  <class 'float'>


In [ ]:
# Make your own floating point number here:



In [9]:
# Some types are compatible for operations like addition
a_sum = an_integer + a_float
print("a_sum has the value ", a_sum)
print("a_sum is of type ", type(a_sum))

a_sum has the value  40.5
a_sum is of type  <class 'float'>


In [10]:
# List
a_list = ['Atmosphere','Cryosphere','Ocean']
print("a_list has the value ", a_list)
print("a_list is of type ", type(a_list))

a_list has the value  ['Atmosphere', 'Cryosphere', 'Ocean']
a_list is of type  <class 'list'>


In [12]:
# Lists can also be added, but the outcome is very different from adding numbers!
# Run the code below to see what happens:
b_list = ['Python', 'Bootcamp']
c_list = ['for', 'Earth', 'Sciences']
print(b_list + c_list)

['Python', 'Bootcamp', 'for', 'Earth', 'Sciences']


In [ ]:
# Make your own list here:



In [ ]:
# Boolean (True or False)
a_bool = (3 == 4) # note that '==' means 'is equal to' whereas '=' assigns a value to a variable
print("a_bool has the value ", a_bool)
print("a_bool is of type ", type(a_bool))

a_bool has the value  False
a_bool is of type  <class 'bool'>


In [ ]:
# Make your own boolean here:



<span style="color:blue"> Task: Look at the following blocks of code, **but don't run them yet**. Before running them, try to predict what the output will be and write that in the Markdown prediction cell below each example.

In [ ]:
first = "2"
second = "2"

result = first + second
print("result = ", result)

**Prediction for the value of `result`:**



In [ ]:
first = 1
second = 1.3

result = first + second
print("result = ", result)

**Prediction for the value of `result`:** 

In [ ]:
first = [1, 2, 3, 5]
second = [2, 3, 5, 7]
result_1 = first+second

result_2 = first[0]+second[0]

print("result_1 =", result_1)
print("result_2 =", result_2)

**Prediction for the value of `result_1`:**

**Prediction for the value of `result_2`:**

## 1.6: Functions

We've talked about saving specific values in code, which are called **variables**. Next, we will talk about saving entire blocks of code to be reused with a specific name. These are called **functions**. 

Functions have 3 parts to think about:
1. The function name
2. The inputs to the function
3. The output from the function

The syntax in Python is as follows:

```python
    #This is a basic function with two inputs and two outputs
    def a_function_name(input_1, input_2):
        #Code to execute here
        output_1 = input_1+5
        output_2 = input_2+8
        
        return output_1, output_2
```

There are a few important pieces to notice here regarding functions
1. The function begins with the word `def`, short for definition, which shows up as a different color, letting us know that it is a keyword and is important.
2. The inputs to the function are given in `()` and each one is separated by a `,`
3. There is a `:` at the end of the function definition line (the first line)
4. The code in the function is tabbed over by 1 tab
5. The outputs also have a keyword before them in the word `return` and are also separated by `,`

### Here is a [helpful](https://www.w3schools.com/python/python_functions.asp) reference guide!

The examples below show some simple functions and how to use them.

In [ ]:
# The following function defined as 'print_full_name' will print the combination of names and doesn't return any values
# When there is no 'return' statement, the function is ended by no longer including a tab before the next line
def print_full_name(first_name, middle_initial, last_name):
    print(first_name + " " + middle_initial + " " + last_name)

# To run the function, we "call" it with specific inputs
print_full_name("Brianna", "C", "Undzis")


<font color='blue'> Task: Call the `print_full_name` function with your own inputs in the cell below.</font>

In [ ]:
# Call the function with names - try with your own name:


In [ ]:
# The following function will multiply an input value given by 5 and return that value
def multiply_by_five(input_value):
    return 5 * input_value

x = 100
five_times = multiply_by_five(x)
print("Five times ", x, " = ", five_times)


<font color='blue'> Task: Call the `multiply_by_five` function with your own inputs in the cell below.</font>

In [ ]:
# Call the function with your own input value:


## 1.7: Importing Packages and Using Functions from Outside the Notebook

### 1.7.1 Making Scripts and Importing your own Functions

<span style="color:blue">Task: Use the file navigation on the left side to find a file called helper_functions.py. Double click and it should open in a new tab. </span>
    
You won't change any of this code, but you can see this file is a collection of the functions made above, plus a few more.

When importing code, you can import all of the package or script, or just a single part.

The code below shows examples of how to use functions from files.

<span style="color:blue">Task: run the following code blocks and change one of the `print_greeting` examples to say your name. </span>

In [13]:
# An example of bringing in one function from a separate script
# this will look for helper_functions.py and import the function `multiply_by_six` from it
from helper_functions import multiply_by_six

six_times = multiply_by_six(10.1)
print("Six times 10.1 = ", six_times)

Six times 10.1 =  60.599999999999994


In [14]:
# An example of bringing in all the functions from a separate script
import helper_functions

# Use the . after the name of the package to access a specific function.
helper_functions.print_greeting("Sean", "D", "Leister")

Hello!
My name is Sean D Leister


In [15]:
# An example of bringing in all the functions but renaming the script with a shorter nickname
import helper_functions as hfs

# Still uses the . to access functions
hfs.print_greeting("Brianna", "C", "Undzis")

Hello!
My name is Brianna C Undzis


### 1.7.2 Using Useful Outside Packages

**Python also allows you to import packages developed by others that can be used to create plots, load data, run statistical analysis, etc.**

We'll start with the following packages that are really useful for importing data and running statistics. You can read more about these packages at the links below, but we will discuss them throughout the bootcamp.

**NOTE: the convention is to have these at the top of each new notebook!** We are breaking that rule for the sake of this lesson, but when you write your own code all of the package imports should go at the top so it is easy to tell what packages are needed.

[Numpy](https://numpy.org/doc/stable/)

[Pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)

[Matplotlib](https://matplotlib.org/stable/contents.html)

In [17]:
# import numpy, pandas and matplotlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

To call a function from one of these imported packages, for example `numpy`, you just need to type the

`imported name + "." + function`

as in this use of the numpy function `array` below:

```python
np.array([1, 2, 3])
```

Which generates the following

In [18]:
np.array([1, 2, 3])

array([1, 2, 3])

<font color='blue'> Task: Try saving a numpy array as a variable, then use the function `np.mean(array_name)` to calculate the mean.

Numpy arrays can also be used within functions. Below, we will generate a new function that will add 1 to each value in a numpy array.

In [19]:
# first, use Numpy to create an array to do some calculations!
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# Create a function that adds 1 to an array.
def add_one(array):
  return array + 1

In [21]:
# run this function and compare to the old array
new_array = add_one(array)
print(new_array)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


<font color='blue'>Task: Now try creating your own function that squares all the values in an array: `array**2`.

In [ ]:
# new_array = ...

# def square() ...

# squared_array = ...

## 1.8: Logic (optional)

Python also gives you the ability to compare data using 'if' statements. In the following, the indented code is run **only if** the value of b is greater than the value of a.

### More guidance on logic can be found [here](https://www.w3schools.com/python/python_conditions.asp)

In [ ]:
a = 33
b = 100

if b > a:
    print('b is greater than a')

In the next block, add a new phrase, `elif`. This tells python what to do **if the first if statement is not true**. Here, elif says that if the values are equal, then that will be printed.

In [ ]:
a = 100
b = 100

if b > a:
    print('b is greater than a')
elif b == a:
    print('b is equal to a')

Finally, you can add an `else` statement that covers **all other situations** (if neither the `if` or `elif` statements are true).

In [ ]:
if b > a:
    print('b is greater than a')
elif b == a:
    print('b is equal to a')
else:
    print('b is less than a')

The `or` operator allows you to create if statements that will be `True` if **one** of the given conditions is true.

In [ ]:
# the operator 'or' can also be included if you want to see if just one condition is true
a = 200
b = 33
c = 500

if a > b or a > c:
    print('one condition is true!')

## 1.9: Importing and Working with Data

We are going to start working with some basic data showing atmospheric temperature in Boulder, CO, with monthly averages.

The data called "boco_air_temp.csv" should be in your file navigator on the left under the "Datasets" folder. To access it, we have to tell Python which folder to look in. All of the datasets for this bootcamp will be in the same folder, so future notebooks will include a cell like this at the top to store the dataset location in a variable called `data_dir` for easy access:


In [22]:
# Set the path to all datasets
# the .. means "go up one folder", and the / separates folder names
# so ../../Datasets/, read left to right, means:
# "go up to Day_1_Intro_to_Python_and_Jupyter, then up again to python_bootcamp_for_earth_sciences, then down into Datasets"
data_dir = '../../Datasets/'

The data is monthly and average annual values at the NOAA Physical Sciences Lab in Boulder, Colorado starting in 1897. In this section we are going to start visualizing the data by introducing two new packages (that you have already imported).

**To import the data, we will rely on the Pandas package and it's `read_csv` function**

In [23]:
data = pd.read_csv(data_dir + 'boco_air_temp.csv')

FileNotFoundError: [Errno 2] No such file or directory: '../../Datasets/boco_air_temp.csv'

Once we have the data saved as a variable, we want to see what it looks like!

In [ ]:
print(data)

This data is read in as a table, similar to what you might have seen in Excel!

To select a specific column, you just need to use one of the indexing functions, so either one of the following:

```python
data['Year']
```
```python
data.Year
```

In [ ]:
print(data['Year'])

In [ ]:
print(data.Year)

### Now that we have read in some data, how would we plot this?

Here is the basic syntax for calling a plot:
```python
plt.plot(xdata,ydata)
```
Remember that `plt` is the name we gave to the package `matplotlib.pyplot` when we imported it

<font color='blue'> Try this yourself by running the cell below.

In [ ]:
plt.plot(data.Year, data.Average)

<font color='blue'> The function plt.plot used above was given two inputs, data.Year and data.Average. Which appears on the x-axis, and which on the y-axis?

You can also add multiple lines to a plot...

In [ ]:
plt.plot(data.Year, data.JAN)
plt.plot(data.Year, data.JUN)

The [documentation](https://matplotlib.org/stable/contents.html) for Matplotlib includes information on how to label your axes, change the colors of lines, add a title, etc. You'll be referencing this extensively during this bootcamp!

<font color='blue'> Copy the two plt.plot commands from above into the cell below, but modify them using explanations in the documentation linked above to make the data.JAN line black, the data.JUN line purple, and add a title explaining what is shown on the plot.